coureurs = {'Jonas Vingegaard': {'equipe' : 'Jumbo-Visma', 'cout': 23,},
'Tiesj Benoot': {'equipe' : 'Jumbo-Visma', 'cout': 14,},
'Wilco Kelderman': {'equipe' : 'Jumbo-Visma', 'cout': 12,},
'Sepp Kuss': {'equipe' : 'Jumbo-Visma', 'cout': 15,},
'Christophe Laporte': {'equipe' : 'Jumbo-Visma', 'cout': 16,},
'Wout van Aert': {'equipe' : 'Jumbo-Visma', 'cout': 23,},
'Dylan van Baarle': {'equipe' : 'Jumbo-Visma', 'cout': 13,},
'Nathan Van Hooydonck': {'equipe' : 'Jumbo-Visma ', 'cout': 6,},
'Tadej Pogacar': {'equipe' : 'UAE Team Emirates ', 'cout': 23,},
'Mikkel Bjerg': {'equipe' : 'UAE Team Emirates ', 'cout': 11,},
'Felix Großschartner': {'equipe' : 'UAE Team Emirates ', 'cout': 14,},
'Vegard Stake Laengen': {'equipe' : 'UAE Team Emirates ', 'cout': 8,},
'Rafal Majka': {'equipe' : 'UAE Team Emirates ', 'cout': 13,},
'Marc Soler': {'equipe' : 'UAE Team Emirates ', 'cout': 11,},
'Matteo Trentin': {'equipe' : 'UAE Team Emirates ', 'cout': 14,},
'Adam Yates': {'equipe' : 'UAE Team Emirates ', 'cout': 17,},
'Egan Bernal': {'equipe' : 'Ineos Grenadiers', 'cout': 14,},
'Jonathan Castroviejo': {'equipe' : 'Ineos Grenadiers', 'cout': 11,},
'Omar Fraile': {'equipe' : 'Ineos Grenadiers', 'cout': 8,},
'Michał Kwiatkowski': {'equipe' : 'Ineos Grenadiers', 'cout': 13,},
'Daniel Felipe Martinez': {'equipe' : 'Ineos Grenadiers', 'cout': 16,},
'Tom Pidcock': {'equipe' : 'Ineos Grenadiers', 'cout': 18,},
'Carlos Rodríguez': {'equipe' : 'Ineos Grenadiers', 'cout': 14,},
'Ben Turner': {'equipe' : 'Ineos Grenadiers', 'cout': 10,},
'David Gaudu': {'equipe' : 'Groupama-FDJ', 'cout': 18,},
'Kevin Geniets': {'equipe' : 'Groupama-FDJ', 'cout': 9,},
'Stefan Küng': {'equipe' : 'Groupama-FDJ', 'cout': 14,},
'Olivier Le Gac': {'equipe' : 'Groupama-FDJ', 'cout': 5,},
'Valentin Madouas': {'equipe' : 'Groupama-FDJ', 'cout': 14,},
'Quentin Pacher': {'equipe' : 'Groupama-FDJ', 'cout': 11,},
'Thibaut Pinot': {'equipe' : 'Groupama-FDJ', 'cout': 14,},
'Lars Van Den Berg': {'equipe' : 'Groupama-FDJ', 'cout': 5,},
'Richard Carapaz': {'equipe' : 'EF Education-Easypost ', 'cout': -1,},
'Andrey Amador': {'equipe' : 'EF Education-Easypost ', 'cout': 9,},
'Alberto Bettiol': {'equipe' : 'EF Education-Easypost ', 'cout': 11,},
'Jhoan Esteban Chaves': {'equipe' : 'EF Education-Easypost ', 'cout': 14,},
'Magnus Cort Nielsen': {'equipe' : 'EF Education-Easypost ', 'cout': 15,},
'Neilson Powless': {'equipe' : 'EF Education-Easypost ', 'cout': 15,},
'James Shaw': {'equipe' : 'EF Education-Easypost ', 'cout': 9,},
'Rigoberto Uran': {'equipe' : 'EF Education-Easypost ', 'cout': 15,},
'Julian Alaphilippe': {'equipe' : 'Soudal Quick-Step', 'cout': 17,},
'Kasper Asgreen': {'equipe' : 'Soudal Quick-Step', 'cout': 11,},
'Rémi Cavagna': {'equipe' : 'Soudal Quick-Step', 'cout': 11,},
'Tim Declercq': {'equipe' : 'Soudal Quick-Step', 'cout': 7,},
'Dries Devenyns': {'equipe' : 'Soudal Quick-Step', 'cout': 8,},
'Fabio Jakobsen': {'equipe' : 'Soudal Quick-Step', 'cout': 21,},
'Yves Lampaert': {'equipe' : 'Soudal Quick-Step', 'cout': 13,},
'Michael Mørkøv': {'equipe' : 'Soudal Quick-Step', 'cout': 9,},
'Mikel Landa': {'equipe' : 'Bahrain Victorious ', 'cout': 17,},
'Nikias Arndt': {'equipe' : 'Bahrain Victorious ', 'cout': 5,},
'Phil Bauhaus': {'equipe' : 'Bahrain Victorious ', 'cout': 13,},
'Pello Bilbao': {'equipe' : 'Bahrain Victorious ', 'cout': 15,},
'Jack Haig': {'equipe' : 'Bahrain Victorious ', 'cout': 14,},
'Matej Mohoric': {'equipe' : 'Bahrain Victorious ', 'cout': 17,},
'Wout Poels': {'equipe' : 'Bahrain Victorious ', 'cout': 9,},
'Fred Wright': {'equipe' : 'Bahrain Victorious ', 'cout': 10,},
'Jai Hindley': {'equipe' : 'Bora - Hansgrohe', 'cout': 18,},
'Emanuel Buchmann': {'equipe' : 'Bora - Hansgrohe', 'cout': 10,},
'Marco Haller': {'equipe' : 'Bora - Hansgrohe', 'cout': 9,},
'Bob Jungels': {'equipe' : 'Bora - Hansgrohe', 'cout': 10,},
'Patrick Konrad': {'equipe' : 'Bora - Hansgrohe', 'cout': 11,},
'Jordi Meeus': {'equipe' : 'Bora - Hansgrohe', 'cout': 14,},
'Nils Politt': {'equipe' : 'Bora - Hansgrohe', 'cout': 7,},
'Danny van Poppel': {'equipe' : 'Bora - Hansgrohe', 'cout': 12,},
'Giulio Ciccone': {'equipe' : 'Lidl - Trek', 'cout': 16,},
'Tony Gallopin': {'equipe' : 'Lidl - Trek', 'cout': 5,},
'Mattias Skjelmose Jensen': {'equipe' : 'Lidl - Trek', 'cout': 17,},
'Alex Kirsch': {'equipe' : 'Lidl - Trek', 'cout': 5,},
'Juan Pedro Lopez': {'equipe' : 'Lidl - Trek', 'cout': 13,},
'Mads Pedersen': {'equipe' : 'Lidl - Trek', 'cout': 18,},
'Quinn Simmons': {'equipe' : 'Lidl - Trek', 'cout': 12,},
'Jasper Stuyven': {'equipe' : 'Lidl - Trek', 'cout': 12,},
'Ben O’Connor': {'equipe' : 'AG2R Citroën Team', 'cout': 18,},
'Clément Berthet': {'equipe' : 'AG2R Citroën Team', 'cout': 10,},
'Benoît Cosnefroy': {'equipe' : 'AG2R Citroën Team', 'cout': 11,},
'Stann Dewulf': {'equipe' : 'AG2R Citroën Team', 'cout': 7,},
'Félix Gall': {'equipe' : 'AG2R Citroën Team', 'cout': 13,},
'Olivier Naesen': {'equipe' : 'AG2R Citroën Team', 'cout': 9,},
'Aurélien Paret-Peintre': {'equipe' : 'AG2R Citroën Team', 'cout': 12,},
'Nans Peters': {'equipe' : 'AG2R Citroën Team', 'cout': 9,},
'Mathieu van der Poel': {'equipe' : 'Alpecin-Deceuninck', 'cout': 22,},
'Silvan Dillier': {'equipe' : 'Alpecin-Deceuninck', 'cout': 8,},
'Michael Gogl': {'equipe' : 'Alpecin-Deceuninck', 'cout': 6,},
'Quinten Hermans': {'equipe' : 'Alpecin-Deceuninck', 'cout': 10,},
'Søren Kragh Andersen': {'equipe' : 'Alpecin-Deceuninck', 'cout': 12,},
'Jasper Philipsen': {'equipe' : 'Alpecin-Deceuninck', 'cout': 21,},
'Jonas Rickaert': {'equipe' : 'Alpecin-Deceuninck', 'cout': 5,},
'Ramon Sinkeldam': {'equipe' : 'Alpecin-Deceuninck', 'cout': 8,},
'Biniam Girmay': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 16,},
'Lilian Calmejane': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 7,},
'Rui Costa': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 12,},
'Louis Meintjes': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 15,},
'Adrien Petit': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 5,},
'Dion Smith': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 8,},
'Mike Teunissen': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 10,},
'Georg Zimmermann': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 10,},
'Guillaume Martin': {'equipe' : 'Cofidis', 'cout': 15,},
'Bryan Coquard': {'equipe' : 'Cofidis', 'cout': 12,},
'Simon Geschke': {'equipe' : 'Cofidis', 'cout': 9,},
'Ion Izagirre': {'equipe' : 'Cofidis', 'cout': 15,},
'Victor Lafay': {'equipe' : 'Cofidis', 'cout': 9,},
'Anthony Perez': {'equipe' : 'Cofidis', 'cout': 6,},
'Alexis Renard': {'equipe' : 'Cofidis', 'cout': 5,},
'Axel Zingle': {'equipe' : 'Cofidis', 'cout': 10,},
'Enric Mas': {'equipe' : 'Movistar Team', 'cout': -1,},
'Ruben Guerreiro': {'equipe' : 'Movistar Team', 'cout': 14,},
'Alex Aranburu': {'equipe' : 'Movistar Team', 'cout': 11,},
'Gorka Izagirre': {'equipe' : 'Movistar Team', 'cout': 9,},
'Matteo Jorgenson': {'equipe' : 'Movistar Team', 'cout': 14,},
'Grego Mühlberger': {'equipe' : 'Movistar Team', 'cout': 9,},
'Nelson Oliveira': {'equipe' : 'Movistar Team', 'cout': 6,},
'Antonio Pedrero': {'equipe' : 'Movistar Team', 'cout': 8,},
'Romain Bardet': {'equipe' : 'Team DSM - Firmenich', 'cout': 17,},
'John Degenkolb': {'equipe' : 'Team DSM - Firmenich', 'cout': 12,},
'Matthews Dinham': {'equipe' : 'Team DSM - Firmenich', 'cout': 5,},
'Alex Edmonson': {'equipe' : 'Team DSM - Firmenich', 'cout': 5,},
'Nils Eekhoff': {'equipe' : 'Team DSM - Firmenich', 'cout': 6,},
'Chris Hamilton': {'equipe' : 'Team DSM - Firmenich', 'cout': 10,},
'Kevin Vermaerke': {'equipe' : 'Team DSM - Firmenich', 'cout': 8,},
'Sam Welsford': {'equipe' : 'Team DSM - Firmenich', 'cout': 13,},
'Michael Woods': {'equipe' : 'Israel - Premier Tech', 'cout': 16,},
'Guillaume Boivin': {'equipe' : 'Israel - Premier Tech', 'cout': 7,},
'Simon Clarke': {'equipe' : 'Israel - Premier Tech', 'cout': 11,},
'Hugo Houle': {'equipe' : 'Israel - Premier Tech', 'cout': 8,},
'Krists Neilands': {'equipe' : 'Israel - Premier Tech', 'cout': 9,},
'Nicholas Schultz': {'equipe' : 'Israel - Premier Tech', 'cout': 6,},
'Corbin Strong': {'equipe' : 'Israel - Premier Tech', 'cout': 7,},
'Dylan Teuns': {'equipe' : 'Israel - Premier Tech', 'cout': 15,},
'Simon Yates': {'equipe' : 'Team Jayco AlUla', 'cout': 17,},
'Lawson Craddock': {'equipe' : 'Team Jayco AlUla', 'cout': 9,},
'Luke Durbridge': {'equipe' : 'Team Jayco AlUla', 'cout': 6,},
'Dylan Groenewegen': {'equipe' : 'Team Jayco AlUla', 'cout': 19,},
'Chris Harper': {'equipe' : 'Team Jayco AlUla', 'cout': 10,},
'Christopher Juul Jensen': {'equipe' : 'Team Jayco AlUla', 'cout': 5,},
'Luka Mezgec': {'equipe' : 'Team Jayco AlUla', 'cout': 9,},
'Elmar Reinders': {'equipe' : 'Team Jayco AlUla', 'cout': 5,},
'Warren Barguil': {'equipe' : 'Team Arkea - Samsic ', 'cout': 11,},
'Jenthe Biermans': {'equipe' : 'Team Arkea - Samsic ', 'cout': 6,},
'Clément Champoussin': {'equipe' : 'Team Arkea - Samsic ', 'cout': 11,},
'Anthony Delaplace': {'equipe' : 'Team Arkea - Samsic ', 'cout': 5,},
'Simon Guglielmi': {'equipe' : 'Team Arkea - Samsic ', 'cout': 6,},
'Matis Louvel': {'equipe' : 'Team Arkea - Samsic ', 'cout': 7,},
'Luca Mozzato': {'equipe' : 'Team Arkea - Samsic ', 'cout': 9,},
'Laurent Pichon': {'equipe' : 'Team Arkea - Samsic ', 'cout': 6,},
'Caleb Ewan': {'equipe' : 'Lotto Dstny', 'cout': 16,},
'Victor Campenaerts': {'equipe' : 'Lotto Dstny', 'cout': 11,},
'Jasper De Buyst': {'equipe' : 'Lotto Dstny', 'cout': 7,},
'Pascal Eenkhoorn': {'equipe' : 'Lotto Dstny', 'cout': 7,},
'Frederik Frison': {'equipe' : 'Lotto Dstny', 'cout': 6,},
'Jacopo Guarnieri': {'equipe' : 'Lotto Dstny', 'cout': -1,},
'Maxim Van Gils': {'equipe' : 'Lotto Dstny', 'cout': 9,},
'Florian Vermeersch': {'equipe' : 'Lotto Dstny', 'cout': 8,},
'Mark Cavendish': {'equipe' : 'Astana Qazaqstan Team', 'cout': 15,},
'Cees Bol': {'equipe' : 'Astana Qazaqstan Team', 'cout': 12,},
'David De La Cruz': {'equipe' : 'Astana Qazaqstan Team', 'cout': 9,},
'Yevgeniy Fedorov': {'equipe' : 'Astana Qazaqstan Team', 'cout': 6,},
'Alexey Lutsenko': {'equipe' : 'Astana Qazaqstan Team', 'cout': 15,},
'Gianni Moscon': {'equipe' : 'Astana Qazaqstan Team', 'cout': 6,},
'Luis Leon Sanchez': {'equipe' : 'Astana Qazaqstan Team', 'cout': -1,},
'Harold Tejada': {'equipe' : 'Astana Qazaqstan Team', 'cout': 8,},
'Alexander Kristoff': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 16,},
'Jonas Abrahamsen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 5,},
'Anthon Charmig': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 7,},
'Tobias Halland Johannessen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 14,},
'Rasmus Tiller': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 8,},
'Torstein Træen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 10,},
'Søren Wærenskjold': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 10,},
'Jonas Gregaard Wilsly': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 8,},
'Peter Sagan': {'equipe' : 'TotalEnergies', 'cout': 13,},
'Edvald Boasson Hagen': {'equipe' : 'TotalEnergies', 'cout': 9,},
'Mathieu Burgaudeau': {'equipe' : 'TotalEnergies', 'cout': 8,},
'Steff Cras': {'equipe' : 'TotalEnergies', 'cout': 8,},
'Valentin Ferron': {'equipe' : 'TotalEnergies', 'cout': 8,},
'Pierre Latour': {'equipe' : 'TotalEnergies', 'cout': 10,},
'Daniel Oss': {'equipe' : 'TotalEnergies', 'cout': 6,},
'Anthony Turgis': {'equipe' : 'TotalEnergies', 'cout': 10,},
}
[ele.update(dict(general=None, montagne=None, points=None, jeune=None, etape=0, total=0, rentabilite=0)) for ele in coureurs.values()]