coureurs = {
    
'Jonas Vingegaard': {'equipe' : 'Visma - Lease a bike', 'cout': 22,},
'Wout van Aert': {'equipe' : 'Visma - Lease a bike', 'cout': 19,},
'Matteo Jorgenson': {'equipe' : 'Visma - Lease a bike', 'cout': 18,},
'Christophe Laporte': {'equipe' : 'Visma - Lease a bike', 'cout': 15,},
'Tiesj Benoot': {'equipe' : 'Visma - Lease a bike', 'cout': 14,},
'Wilco Kelderman': {'equipe' : 'Visma - Lease a bike', 'cout': 12,},
'Jan Tratnik': {'equipe' : 'Visma - Lease a bike', 'cout': 8,},
'Bart Lemmen': {'equipe' : 'Visma - Lease a bike ', 'cout': 7,},

'Tadej Pogacar': {'equipe' : 'UAE Team Emirates ', 'cout': 25,},
'Adam Yates': {'equipe' : 'UAE Team Emirates ', 'cout': 20,},
'Joao Almeida': {'equipe' : 'UAE Team Emirates ', 'cout': 19,},
'Juan Ayuso': {'equipe' : 'UAE Team Emirates ', 'cout': 19,},
'Pavel Sivakov': {'equipe' : 'UAE Team Emirates ', 'cout': 14,},
'Marc Soler': {'equipe' : 'UAE Team Emirates ', 'cout': 11,},
'Tim Wellens': {'equipe' : 'UAE Team Emirates ', 'cout': 10,},
'Nils Politt': {'equipe' : 'UAE Team Emirates ', 'cout': 9,},

'Carlos Rodríguez': {'equipe' : 'Ineos Grenadiers', 'cout': 18,},
'Geraint Thomas': {'equipe' : 'Ineos Grenadiers', 'cout': 18,},
'Tom Pidcock': {'equipe' : 'Ineos Grenadiers', 'cout': 18,},
'Egan Bernal': {'equipe' : 'Ineos Grenadiers', 'cout': 17,},
'Michał Kwiatkowski': {'equipe' : 'Ineos Grenadiers', 'cout': 12,},
'Laurens de Plus': {'equipe' : 'Ineos Grenadiers', 'cout': 12,},
'Jonathan Castroviejo': {'equipe' : 'Ineos Grenadiers', 'cout': 11,},
'Ben Turner': {'equipe' : 'Ineos Grenadiers', 'cout': 10,},

'David Gaudu': {'equipe' : 'Groupama-FDJ', 'cout': 16,},
'Stefan Küng': {'equipe' : 'Groupama-FDJ', 'cout': 14,},
'Valentin Madouas': {'equipe' : 'Groupama-FDJ', 'cout': 12,},
'Lenny Martinez': {'equipe' : 'Groupama-FDJ', 'cout': 11,},
'Romain Grégoire': {'equipe' : 'Groupama-FDJ', 'cout': 11,},
'Quentin Pacher': {'equipe' : 'Groupama-FDJ', 'cout': 10,},
'Clément Russo': {'equipe' : 'Groupama-FDJ', 'cout': 9,},
'Kevin Geniets': {'equipe' : 'Groupama-FDJ', 'cout': 8,},

'Richard Carapaz': {'equipe' : 'EF Education-Easypost ', 'cout': 18,},
'Neilson Powless': {'equipe' : 'EF Education-Easypost ', 'cout': 15,},
'Stefan Bisseger': {'equipe' : 'EF Education-Easypost ', 'cout': 13,},
'Ben Healy': {'equipe' : 'EF Education-Easypost ', 'cout': 13,},
'Alberto Bettiol': {'equipe' : 'EF Education-Easypost ', 'cout': 11,},
'Marijn van den berg': {'equipe' : 'EF Education-Easypost ', 'cout': 11,},
'Rui Costa': {'equipe' : 'EF Education-Easypost ', 'cout': 12,},
'Sean Quinn': {'equipe' : 'EF Education-Easypost ', 'cout': 9,},

'Remco Evenepoel': {'equipe' : 'Soudal Quick-Step', 'cout': 20,},
'Mikel Landa': {'equipe' : 'Soudal Quick-Step', 'cout': 16,},
'Ilan Van Wilder': {'equipe' : 'Soudal Quick-Step', 'cout': 13,},
'Yves Lampaert': {'equipe' : 'Soudal Quick-Step', 'cout': 12,},
'Jan Hirt': {'equipe' : 'Soudal Quick-Step', 'cout': 11,},
'Louis Vervaeke': {'equipe' : 'Soudal Quick-Step', 'cout': 7,},
'Gianni Moscon': {'equipe' : 'Soudal Quick-Step', 'cout': 7,},

'Santiago Buitrago': {'equipe' : 'Bahrain Victorious ', 'cout': 17,},
'Matej Mohoric': {'equipe' : 'Bahrain Victorious ', 'cout': 17,},
'Phil Bauhaus': {'equipe' : 'Bahrain Victorious ', 'cout': 15,},
'Pello Bilbao': {'equipe' : 'Bahrain Victorious ', 'cout': 15,},
'Jack Haig': {'equipe' : 'Bahrain Victorious ', 'cout': 14,},
'Wout Poels': {'equipe' : 'Bahrain Victorious ', 'cout': 11,},
'Fred Wright': {'equipe' : 'Bahrain Victorious ', 'cout': 11,},
'Nikias Arndt': {'equipe' : 'Bahrain Victorious ', 'cout': 5,},

'Primoz Roglic': {'equipe' : 'Bora - Hansgrohe', 'cout': 21,},
'Alexander Vlasov': {'equipe' : 'Bora - Hansgrohe', 'cout': 18,},
'Jai Hindley': {'equipe' : 'Bora - Hansgrohe', 'cout': 17,},
'Matteo Sobrero': {'equipe' : 'Bora - Hansgrohe', 'cout': 11,},
'Danny van Poppel': {'equipe' : 'Bora - Hansgrohe', 'cout': 11,},
'Marco Haller': {'equipe' : 'Bora - Hansgrohe', 'cout': 8,},
'Bob Jungels': {'equipe' : 'Bora - Hansgrohe', 'cout': 8,},
'Nico Denz': {'equipe' : 'Bora - Hansgrohe', 'cout': 7,},

'Mads Pedersen': {'equipe' : 'Lidl - Trek', 'cout': 18,},
'Giulio Ciccone': {'equipe' : 'Lidl - Trek', 'cout': 16,},
'Jasper Stuyven': {'equipe' : 'Lidl - Trek', 'cout': 12,},
'Toms Skujins': {'equipe' : 'Lidl - Trek', 'cout': 9,},
'Ryan Gibbons': {'equipe' : 'Lidl - Trek', 'cout': 8,},
'Julien Bernard': {'equipe' : 'Lidl - Trek', 'cout': 7,},
'Tim Declercq': {'equipe' : 'Lidl - Trek', 'cout': 7,},
'Carlos Verona': {'equipe' : 'Lidl - Trek', 'cout': 6,},

'Félix Gall': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 17,},
'Sam Benett': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 16,},
'Nicolas Prodhomme': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 12,},
'Bruno Armirail': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 11,},
'Dorian Godon': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 11,},
'Paul Lapeira': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 10,},
'Nans Peters': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 9,},
'Olivier Naesen': {'equipe' : 'Decathlon AG2R La Mondiale', 'cout': 9,},

'Jasper Philipsen': {'equipe' : 'Alpecin-Deceuninck', 'cout': 23,},
'Mathieu van der Poel': {'equipe' : 'Alpecin-Deceuninck', 'cout': 22,},
'Soren Kragh Andersen': {'equipe' : 'Alpecin-Deceuninck', 'cout': 12,},
'Axel Laurance': {'equipe' : 'Alpecin-Deceuninck', 'cout': 10,},
'Gianni Vermeersch': {'equipe' : 'Alpecin-Deceuninck', 'cout': 9,},
'Silvan Dillier': {'equipe' : 'Alpecin-Deceuninck', 'cout': 8,},
'Robbe Ghys': {'equipe' : 'Alpecin-Deceuninck', 'cout': 6,},
'Jonas Rickaert': {'equipe' : 'Alpecin-Deceuninck', 'cout': 6,},

'Biniam Girmay': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 15,},
'Gerben Thijssen': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 15,},
'Louis Meintjes': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 15,},
'Georg Zimmermann': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 10,},
'Hugo Page': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 10,},
'Kobe Goossens': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 9,},
'Laurenz Rex': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 9,},
'Mike Teunissen': {'equipe' : 'Intermarché - Circus - Wanty', 'cout': 9,},

'Guillaume Martin': {'equipe' : 'Cofidis', 'cout': 14,},
'Ion Izagirre': {'equipe' : 'Cofidis', 'cout': 13,},
'Bryan Coquard': {'equipe' : 'Cofidis', 'cout': 12,},
'Jesus Herrada': {'equipe' : 'Cofidis', 'cout': 10,},
'Axel Zingle': {'equipe' : 'Cofidis', 'cout': 10,},
'Simon Geschke': {'equipe' : 'Cofidis', 'cout': 9,},
'Piet Allegaert': {'equipe' : 'Cofidis', 'cout': 6,},
'Alexis Renard': {'equipe' : 'Cofidis', 'cout': 5,},

'Enric Mas': {'equipe' : 'Movistar Team', 'cout': 18,},
'Fernando Gaviria': {'equipe' : 'Movistar Team', 'cout': 16,},
'Oier Lazkano': {'equipe' : 'Movistar Team', 'cout': 15,},
'Davide Formolo': {'equipe' : 'Movistar Team', 'cout': 11,},
'Alex Aranburu': {'equipe' : 'Movistar Team', 'cout': 11,},
'Gregor Mühlberger': {'equipe' : 'Movistar Team', 'cout': 9,},
'Javier Romo': {'equipe' : 'Movistar Team', 'cout': 7,},
'Nelson Oliveira': {'equipe' : 'Movistar Team', 'cout': 6,},

'Fabio Jakobsen': {'equipe' : 'Team DSM - Firmenich', 'cout': 17,},
'Romain Bardet': {'equipe' : 'Team DSM - Firmenich', 'cout': 15,},
'Oscar Onley': {'equipe' : 'Team DSM - Firmenich', 'cout': 12,},
'John Degenkolb': {'equipe' : 'Team DSM - Firmenich', 'cout': 10,},
'Warren Barguil': {'equipe' : 'Team DSM - Firmenich', 'cout': 10,},
'Frank Van den Broek': {'equipe' : 'Team DSM - Firmenich', 'cout': 7,},
'Nils Eekhoff': {'equipe' : 'Team DSM - Firmenich', 'cout': 6,},
'Bram Welten': {'equipe' : 'Team DSM - Firmenich', 'cout': 5,},

'Derek Gee': {'equipe' : 'Israel - Premier Tech', 'cout': 16,},
'Stephen Williams': {'equipe' : 'Israel - Premier Tech', 'cout': 15,},
'Pascal Ackermann': {'equipe' : 'Israel - Premier Tech', 'cout': 14,},
'Jake Stewart': {'equipe' : 'Israel - Premier Tech', 'cout': 11,},
'Krists Neilands': {'equipe' : 'Israel - Premier Tech', 'cout': 11,},
'Jakob Fuglsang': {'equipe' : 'Israel - Premier Tech', 'cout': 9,},
'Hugo Houle': {'equipe' : 'Israel - Premier Tech', 'cout': 8,},
'Guillaume Boivin': {'equipe' : 'Israel - Premier Tech', 'cout': 7,},

'Simon Yates': {'equipe' : 'Team Jayco AlUla', 'cout': 17,},
'Dylan Groenewegen': {'equipe' : 'Team Jayco AlUla', 'cout': 17,},
'Michael Matthews': {'equipe' : 'Team Jayco AlUla', 'cout': 16,},
'Chris Harper': {'equipe' : 'Team Jayco AlUla', 'cout': 12,},
'Luka Mezgec': {'equipe' : 'Team Jayco AlUla', 'cout': 9,},
'Christopher Juul-Jansen': {'equipe' : 'Team Jayco AlUla', 'cout': 7,},
'Luke Durbridge': {'equipe' : 'Team Jayco AlUla', 'cout': 6,},
'Elmar Reinders': {'equipe' : 'Team Jayco AlUla', 'cout': 5,},

'Arnaud Démare': {'equipe' : 'Team Arkea - Samsic ', 'cout': 14,},
'Kévin Vauquelin': {'equipe' : 'Team Arkea - Samsic ', 'cout': 12,},
'Daniel McLay': {'equipe' : 'Team Arkea - Samsic ', 'cout': 12,},
'Amaury Capiot': {'equipe' : 'Team Arkea - Samsic ', 'cout': 12,},
'Cristian Rodriguez': {'equipe' : 'Team Arkea - Samsic ', 'cout': 11,},
'Luca Mozzato': {'equipe' : 'Team Arkea - Samsic ', 'cout': 11,},
'Clément Champoussin': {'equipe' : 'Team Arkea - Samsic ', 'cout': 11,},
'Raul Garcia Pierna': {'equipe' : 'Team Arkea - Samsic ', 'cout': 9,},

'Arnaud de Lie': {'equipe' : 'Lotto Dstny', 'cout': 18,},
'Maxim Van Gils': {'equipe' : 'Lotto Dstny', 'cout': 12,},
'Victor Campenaerts': {'equipe' : 'Lotto Dstny', 'cout': 11,},
'Brent Van Moer': {'equipe' : 'Lotto Dstny', 'cout': 9,},
'Harm Vanhoucke': {'equipe' : 'Lotto Dstny', 'cout': 8,},
'Jarrad Eriks Drizners': {'equipe' : 'Lotto Dstny', 'cout': 6,},
'Cédric Beullens': {'equipe' : 'Lotto Dstny', 'cout': 6,},
'Sébastien Grignard': {'equipe' : 'Lotto Dstny', 'cout': 5,},

'Mark Cavendish': {'equipe' : 'Astana Qazaqstan Team', 'cout': 15,},
'Alexey Lutsenko': {'equipe' : 'Astana Qazaqstan Team', 'cout': 14,},
'Cees Bol': {'equipe' : 'Astana Qazaqstan Team', 'cout': 12,},
'Davide Ballerini': {'equipe' : 'Astana Qazaqstan Team', 'cout': 11,},
'Harold Tejada': {'equipe' : 'Astana Qazaqstan Team', 'cout': 10,},
'Yevgeniy Fedorov': {'equipe' : 'Astana Qazaqstan Team', 'cout': 6,},
'Michael Morkov': {'equipe' : 'Astana Qazaqstan Team', 'cout': 9,},

'Alexander Kristoff': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 15,},
'Magnus Cort Nielsen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 14,},
'Tobias Johannessen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 13,},
'Odd Christian Eiking': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 11,},
'Søren Wærenskjold': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 11,},
'Johannes Kulset': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 10,},
'Rasmus Tiller': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 9,},
'Jonas Abrahamsen': {'equipe' : 'Uno-X Pro Cycling Team', 'cout': 7,},

'Jordan Jegat': {'equipe' : 'TotalEnergies', 'cout': 11,},
'Sandy Dujardin': {'equipe' : 'TotalEnergies', 'cout': 10,},
'Steff Cras': {'equipe' : 'TotalEnergies', 'cout': 10,},
'Anthony Turgis': {'equipe' : 'TotalEnergies', 'cout': 9,},
'Mathieu Burgaudeau': {'equipe' : 'TotalEnergies', 'cout': 8,},
'Mattéo Vercher': {'equipe' : 'TotalEnergies', 'cout': 6,},
'Thomas Gachignard': {'equipe' : 'TotalEnergies', 'cout': 6,},
'Fabien Grellier': {'equipe' : 'TotalEnergies', 'cout': 6,},
}
[ele.update(dict(general=None, montagne=None, points=None, jeune=None, etape=0, total=0, rentabilite=0)) for ele in coureurs.values()]